INSERT INTO [dbo].[grupo_hora]([codigo],[descripcion]) VALUES(1,'00:00 a 05:59')
INSERT INTO [dbo].[grupo_hora]([codigo],[descripcion]) VALUES(2,'06:00 a 11:59')
INSERT INTO [dbo].[grupo_hora]([codigo],[descripcion]) VALUES(3,'12:00 a 17:59')
INSERT INTO [dbo].[grupo_hora]([codigo],[descripcion]) VALUES(4,'18:00 a 23:59')

INSERT INTO [dbo].[grupo_tiempo]([codigo],[descripcion]) VALUES(1,'Mañana')
INSERT INTO [dbo].[grupo_tiempo]([codigo],[descripcion]) VALUES(2,'Tarde')
INSERT INTO [dbo].[grupo_tiempo]([codigo],[descripcion]) VALUES(3,'Noche')

INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(1,'Enero')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(2,'Febrero')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(3,'Marzo')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(4,'Abril')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(5,'Mayo')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(6,'Junio')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(7,'Julio')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(8,'Agosto ')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(9,'Septiembre')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(10,'Octubre')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(11,'Noviembre')
INSERT INTO [dbo].[mes_ocurrencia]([codigo],[descripcion]) VALUES(12,'Diciembre')

INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(1,'Lunes')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(2,'Martes')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(3,'Miércoles')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(4,'Jueves')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(5,'Viernes')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(6,'Sábado')
INSERT INTO [dbo].[dia_ocurrencia]([codigo],[descripcion]) VALUES(7,'Domingo')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(1,'Guatemala')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(2,'El Progreso')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(3,'Sacatepéquez')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(4,'Chimaltenango')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(5,'Escuintla')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(6,'Santa Rosa')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(7,'Sololá')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(8,'Totonicapán')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(9,'Quetzaltenango')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(10,'Suchitepéquez')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(11,'Retalhuleu')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(12,'San Marcos')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(13,'Huehuetenango')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(14,'Quiché')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(15,'Baja Verapaz')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(16,'Alta Verapaz')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(17,'Petén')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(18,'Izabal')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(19,'Zacapa')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(20,'Chiquimula')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(21,'Jalapa')
INSERT INTO [dbo].[departamento]([codigo],[descripcion]) VALUES(22,'Jutiapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(101,'Guatemala ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(102,'Santa Catarina Pinula ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(103,'San José Pinula')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(104,'San José del Golfo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(105,'Palencia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(106,'Chinautla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(107,'San Pedro Ayampuc')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(108,'Mixco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(109,'San Pedro Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(110,'San Juan Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(111,'San Raymundo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(112,'Chuarrancho')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(113,'Fraijanes')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(114,'Amatitlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(115,'Villa Nueva')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(116,'Villa Canales')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(117,'Petapa ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(201,'Guastatoya')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(202,'Morazán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(203,'San Agustín Acasaguastlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(204,'San Cristóbal Acasaguastlán ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(205,'El Jícaro')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(206,'Sansare')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(207,'Sanarate')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(208,'San Antonio la Paz')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(301,'Antigua Guatemala')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(302,'Jocotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(303,'Pastores')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(304,'Sumpango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(305,'Santo Domingo Xenacoj')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(306,'Santiago Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(307,'San Bartolomé Milpas Altas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(308,'San Lucas Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(309,'Santa Lucía Milpas Altas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(310,'Magdalena Milpas Altas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(311,'Santa María de Jesús')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(312,'Ciudad Vieja')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(313,'San Miguel Dueñas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(314,'San Juan Alotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(315,'San Antonio Aguas Calientes')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(316,'Santa Catarina Barahona')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(401,'Chimaltenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(402,'San José  Poaquíl')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(403,'San Martín Jilotepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(404,'Comalapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(405,'Santa Apolonia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(406,'Tecpán Guatemala')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(407,'Patzún ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(408,'San Miguel Pochuta')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(409,'Patzicía')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(410,'Santa Cruz Balanyá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(411,'Acatenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(412,'Yepocapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(413,'San Andrés Itzapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(414,'Parramos')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(415,'Zaragoza')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(416,'El Tejar')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(501,'Escuintla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(502,'Santa Lucía Cotzumalguapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(503,'La Democracia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(504,'Siquinalá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(505,'Masagua')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(506,'Tiquisate')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(507,'La Gomera')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(508,'Guanagazapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(509,'San José')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(510,'Iztapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(511,'Palín')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(512,'San Vicente Pacaya')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(513,'Nueva Concepción')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(514,'Sipacate')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(601,'Cuilapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(602,'Barberena')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(603,'Santa Rosa de Lima')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(604,'Casillas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(605,'San Rafael las Flores')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(606,'Oratorio')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(607,'San Juan Tecuaco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(608,'Chiquimulilla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(609,'Taxisco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(610,'Santa María Ixhuatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(611,'Guazacapán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(612,'Santa Cruz el Naranjo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(613,'Pueblo Nuevo Viñas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(614,'Nueva Santa Rosa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(701,'Sololá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(702,'San José Chacayá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(703,'Santa María Visitación')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(704,'Santa Lucía Utatlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(705,'Nahualá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(706,'Santa Catarina Ixtahuacán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(707,'Santa Clara la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(708,'Concepción')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(709,'San Andrés Semetabaj')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(710,'Panajachel')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(711,'Santa Catarina Palopó')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(712,'San Antonio Palopó')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(713,'San Lucas Tolimán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(714,'Santa Cruz la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(715,'San Pablo la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(716,'San Marcos la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(717,'San Juan la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(718,'San Pedro la Laguna')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(719,'Santiago Atitlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(801,'Totonicapán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(802,'San Cristóbal Totonicapán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(803,'San Francisco el Alto')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(804,'San Andrés Xecul')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(805,'Momostenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(806,'Santa María Chiquimula')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(807,'Santa Lucía la Reforma')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(808,'San Bartolo Aguas Calientes')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(901,'Quetzaltenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(902,'Salcajá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(903,'Olintepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(904,'San Carlos Sija')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(905,'Sibilia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(906,'Cabricán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(907,'Cajolá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(908,'San Miguel Siguilá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(909,'San Juan Ostuncalco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(910,'San Mateo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(911,'Concepción Chiquirichapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(912,'San Martín Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(913,'Almolonga')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(914,'Cantel')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(915,'Huitán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(916,'Zunil')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(917,'Colomba')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(918,'San Francisco la Unión')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(919,'El Palmar')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(920,'Coatepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(921,'Génova')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(922,'Flores Costa Cuca ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(923,'La Esperanza')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(924,'Palestina de los Altos')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1001,'Mazatenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1002,'Cuyotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1003,'San Francisco Zapotitlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1004,'San Bernardino')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1005,'San José el Ídolo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1006,'Santo Domingo Suchitepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1007,'San Lorenzo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1008,'Samayac')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1009,'San Pablo Jocopilas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1010,'San Antonio Suchitepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1011,'San Miguel Panán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1012,'San Gabriel ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1013,'Chicacao')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1014,'Patulul')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1015,'Santa Bárbara')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1016,'San Juan Bautista')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1017,'Santo Tomas la Unión')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1018,'Zunilito')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1019,'Pueblo Nuevo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1020,'Río Bravo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1021,'San José La Máquina')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1101,'Retalhuleu')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1102,'San Sebastián')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1103,'Santa Cruz Muluá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1104,'San Martín Zapotitlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1105,'San Felipe Retalhuleu')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1106,'San Andrés Villa Seca')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1107,'Champerico')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1108,'Nuevo San Carlos')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1109,'El Asintal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1201,'San Marcos')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1202,'San Pedro Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1203,'San Antonio Sacatepéquez')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1204,'Comitancillo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1205,'San Miguel Ixtahuacán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1206,'Concepción Tutuapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1207,'Tacaná ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1208,'Sibinal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1209,'Tajumulco ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1210,'Tejutla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1211,'San Rafael Pie de la Cuesta')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1212,'Nuevo Progreso')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1213,'El Tumbador')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1214,'El Rodeo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1215,'Malacatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1216,'Catarina')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1217,'Ayutla ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1218,'Ocós')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1219,'San Pablo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1220,'El Quetzal ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1221,'La Reforma')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1222,'Pajapita')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1223,'Ixchiguán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1224,'San José Ojetenam')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1225,'San Cristóbal Cucho')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1226,'Sipacapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1227,'Esquipulas Palo Gordo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1228,'Río Blanco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1229,'San Lorenzo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1230,'La Blanca')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1301,'Huehuetenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1302,'Chiantla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1303,'Malacatancito')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1304,'Cuilco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1305,'Nentón')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1306,'San Pedro Necta')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1307,'Jacaltenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1308,'San Pedro Soloma')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1309,'San Ildefonso Ixtahuacán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1310,'Santa Bárbara')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1311,'La Libertad')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1312,'La Democracia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1313,'San Miguel Acatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1314,'San Rafael La Independencia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1315,'Todos Santos Cuchumatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1316,'San Juan Atitán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1317,'Santa Eulalia')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1318,'San Mateo Ixtatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1319,'Colotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1320,'San Sebastián Huehuetenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1321,'Tectitán ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1322,'Concepción Huista')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1323,'San Juan Ixcoy')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1324,'San Antonio Huista')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1325,'San Sebastián Coatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1326,'Barrillas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1327,'Aguacatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1328,'San Rafael Petzal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1329,'San Gaspar Ixchil')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1330,'Santiago Chimaltenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1331,'Santa Ana Huista')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1332,'Unión Cantinil')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1333,'Petatán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1401,'Santa Cruz del Quiché')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1402,'Chiché')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1403,'Chinique')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1404,'Zacualpa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1405,'Chajul')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1406,'Chichicastenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1407,'Patzité')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1408,'San Antonio Ilotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1409,'San Pedro Jocopilas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1410,'Cunén')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1411,'San Juan Cotzal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1412,'Joyabaj')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1413,'Santa María Nebaj')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1414,'San Andrés Sajcabajá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1415,'San Miguel Uspantán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1416,'Sacapulas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1417,'San Bartolomé Jocotenango')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1418,'Canillá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1419,'Chicamán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1420,'Ixcán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1421,'Pachalum')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1501,'Salamá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1502,'San Miguel Chicaj')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1503,'Rabinal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1504,'Cubulco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1505,'Granados')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1506,'El Chol')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1507,'San Jerónimo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1508,'Purulhá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1601,'Cobán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1602,'Santa Cruz Verapaz')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1603,'San Cristóbal Verapaz')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1604,'Tactic')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1605,'Tamahú')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1606,'Tucurú')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1607,'Panzós')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1608,'Senahú')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1609,'San Pedro Carchá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1610,'San Juan Chamelco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1611,'Lanquín')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1612,'Cahabón')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1613,'Chisec')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1614,'Chahal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1615,'Fray Bartolomé de las Casas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1616,'Santa Catarina La Tinta')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1617,'Raxruhá')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1701,'Flores')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1702,'San José')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1703,'San Benito')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1704,'San Andrés')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1705,'La Libertad')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1706,'San Francisco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1707,'Santa Ana')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1708,'Dolores')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1709,'San Luis')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1710,'Sayaxché')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1711,'Melchor de Mencos')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1712,'Poptún')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1713,'Las Cruces')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1714,'El Chal')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1801,'Puerto Barrios')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1802,'Livingston')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1803,'El Estor')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1804,'Morales')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1805,'Los Amates')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1901,'Zacapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1902,'Estanzuela')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1903,'Río Hondo')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1904,'Gualán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1905,'Teculután')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1906,'Usumatlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1907,'Cabañas ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1908,'San Diego')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1909,'La Unión')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1910,'Huité')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(1911,'San Jorge')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2001,'Chiquimula')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2002,'San José la Arada')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2003,'San Juan Ermita')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2004,'Jocotán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2005,'Camotán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2006,'Olopa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2007,'Esquipulas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2008,'Concepción las Minas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2009,'Quezaltepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2010,'San Jacinto ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2011,'Ipala')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2101,'Jalapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2102,'San Pedro Pinula')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2103,'San Luis Jilotepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2104,'San Manuel Chaparrón')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2105,'San Carlos Alzatate')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2106,'Monjas')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2107,'Mataquescuintla')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2201,'Jutiapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2202,'El Progreso')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2203,'Santa Catarina Mita')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2204,'Agua Blanca')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2205,'Asunción Mita')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2206,'Yupiltepeque')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2207,'Atescatempa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2208,'Jerez ')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2209,'El Adelanto')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2210,'Zapotitlán')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2211,'Comapa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2212,'Jalpatagua')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2213,'Conguaco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2214,'Moyuta')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2215,'Pasaco')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2216,'San José Acatempa')
INSERT INTO [dbo].[municipio]([codigo],[descripcion]) VALUES(2217,'Quesada')

INSERT INTO [dbo].[sexo]([codigo],[descripcion]) VALUES(1,'Hombre')
INSERT INTO [dbo].[sexo]([codigo],[descripcion]) VALUES(2,'Mujer')
INSERT INTO [dbo].[sexo]([codigo],[descripcion]) VALUES(9,'Ignorado')

INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(1,'Menor de 15')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(2,'15-19')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(3,'20-24')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(4,'25-29')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(5,'30-34')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(6,'35-39')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(7,'40-44')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(8,'45-49')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(9,'50-54')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(10,'55-59')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(11,'60-64')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(12,'65-69')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(13,'70-74')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(14,'75-80')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(15,'80 y más')
INSERT INTO [dbo].[grupo_edad]([codigo],[descripcion]) VALUES(16,'Ignorado')



INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(1,'Automóvil')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(2,'Camioneta sport o blazer')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(3,'Pick up')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(4,'Motocicleta')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(5,'Camión')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(6,'Cabezal')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(7,'Bus extraurbano')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(8,'Jeep')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(9,'Microbús')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(10,'Taxi')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(11,'Panel')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(12,'Bus urbano')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(13,'Tractor')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(14,'Moto taxi')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(15,'Furgón')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(16,'Grúa')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(17,'Bus escolar')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(18,'Bicicleta')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(19,'Avioneta')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(20,'Montacargas')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(21,'Bus militar')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(22,'Cuatrimoto')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(23,'Furgoneta')
INSERT INTO [dbo].[tipo_vehiculo]([codigo],[descripcion]) VALUES(99,'Ignorado')

INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(1,'Rojo')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(2,'Blanco')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(3,'Azul')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(4,'Gris')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(5,'Negro')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(6,'Verde')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(7,'Amarillo')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(8,'Celeste')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(9,'Corinto')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(10,'Café')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(11,'Beige')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(12,'Turquesa')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(13,'Marfil')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(14,'Anaranjado')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(15,'Morado')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(16,'Rosado')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(17,'Varios colores')
INSERT INTO [dbo].[color_vehiculo]([codigo],[descripcion]) VALUES(99,'Ignorado')



INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(1,'Colisión')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(2,'Choque')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(3,'Vuelco')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(4,'Caída')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(5,'Atropello')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(6,'Derrape')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(7,'Embarranco')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(8,'Encuneto')
INSERT INTO [dbo].[tipo_evento]([codigo],[descripcion]) VALUES(99,'Ignorado')

INSERT INTO [dbo].[resultado_accidente]([codigo],[descripcion]) VALUES(1,'Fallecido')
INSERT INTO [dbo].[resultado_accidente]([codigo],[descripcion]) VALUES(2,'Lesionado')
INSERT INTO [dbo].[resultado_accidentado]([codigo],[descripcion]) VALUES(1,'Internado')
INSERT INTO [dbo].[resultado_accidentado]([codigo],[descripcion]) VALUES(2,'No internado')
INSERT INTO [dbo].[resultado_accidentado]([codigo],[descripcion]) VALUES(9,'Ignorado')


INSERT INTO [dbo].[estado_conductor]([codigo],[descripcion]) VALUES(1,'No ebrio')
INSERT INTO [dbo].[estado_conductor]([codigo],[descripcion]) VALUES(2,'Ebrio')
INSERT INTO [dbo].[estado_conductor]([codigo],[descripcion]) VALUES(9,'Ignorado')
